#pragma once

enum class REPOS_DIR { FRONT, 
	FARLEFT, FARRIGHT, FARLEFTBACK, FARRIGHTBACK, 
	LEFT, RIGHT, LEFTBACK, RIGHTBACK, 
	VRYNEAR, NONE 
};

enum class ANJ_ACTION { ROAR, BITE, CONTIN_BITE, CLAW_SCRATCH, TAIL_SLAM, TAIL_SWEEP, BODY_SLAM, FORWARD_ATK, RUSH, NONE };